### ISSUE TITLE
Macrobody Facets in Cell Definition

### ISSUE THREAD

**Issue by SterlingButters** [idaholab/MontePy#350]
**Describe the bug**
MontePy reports `"ValueError: invalid literal for int() with base 10: '1000.6'`

I'm guessing it was assumed that cell surfaces were always integers but if using macrobody facets to define a cell this might not be the case

**Comment by MicahGale** [comment]
You are correct there was an implicit assumption that only integer surface and cell identifiers will be used.

There is no easy workaround currently. This will require fully implementing macro-bodies and their subsurface identifiers.

Side note: I was looking through the MCNP manuals to see if we can blame it on their documentation. I realized they never formally define a complete grammar for cells. They say you make a geometry with "operators". Operating on what? They never formally define that in their syntax grammar.

**Comment by MicahGale** [comment]
How big of an issue for you is this? My group doesn't really use macrobodies hence why they aren't implemented. 

I forgot the obvious workaround for now: don't use macrobodies, and only use primitive surfaces.

**Comment by SterlingButters** [comment]
I mean realistically I've gotten by without MontePy until now and my workflow, while clunky, works. 

That said, we/I prefer macrobodies and hence we use them as often as primitive surfaces so personally I'd like to see them implemented (I'd be surprised too if I was the only one).

**Comment by MicahGale** [comment]
I'm going to close this as it is more feature related, and track the work in #354.
