### ISSUE TITLE
Trailing comments aren't being properly transferred

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#352]
While working on #351 I noticed that `cell.comments` was wrong. 

The following cell:

``` 
100103  3926  5.00000E-02 (-102002          -36425  36426):   $ Lower Rodlet Sodium Bond
                          (-102002  169239  -36426  36427)    u=424 
c
c comment for next cell... 
c
... next cell
```

Had too many comments in `cell.comments`

``` python
In [13]: cell.comments
Out[13]:
[COMMENT:
 $ Lower Rodlet Sodium Bond,
 COMMENT:
 c,
 COMMENT:
 c comment for next cell... 
 COMMENT:
 c,
```

**Additional context**
Version: `0.3.0dev1`

Note to self: see if next cell actually got parsed

**Comment by MicahGale** [comment]
@tjlaboss could you test this out on 0.3.2? I feel like this should be resolved by one of the recent releases.

**Comment by MicahGale** [comment]
@MicahGale test this.

**Comment by tjlaboss** [comment]
> @tjlaboss could you test this out on 0.3.2? I feel like this should be resolved by one of the recent releases.

I didn't post it here, but I was able to reproduce the same behavior with 0.3.3: cells ate up the following comments, leading to some non-breaking but awkward behavior (see #484).

**Comment by MicahGale** [comment]
Did it lead to anything not parsing?

If not I'm thinking of calling this "low priority".
