### ISSUE TITLE
All raised exceptions should print line/number of occurrence in deck 

### ISSUE THREAD

**Issue by SterlingButters** [idaholab/MontePy#362]
**Is your feature request related to a problem? Please describe.**
Only some exceptions print the locations of read-errors in the input deck I am suggesting this be implemented for all exceptions e.g. `UnsupportedFeature`. This would make debugging much easier.

**Comment by MicahGale** [comment]
Thinking about this more. I think all of the relevant errors should look a lot like `ParserError`. I'm thinking of making an abstract class that handles the annoying stuff of highlighting the specific problem child. 

This will take a lot of refactoring, but it should be very much so worthwhile. For instance #355, would have been so much easier to debug. 

Also any improvements that are needed for the `ParserError` printing @SterlingButters, or is it a good template?

e.g.,

``` python
    raise ParsingError(
montepy.errors.ParsingError:     testRead.imcnp, line 3

         2| C this is a comment
    >    3| read file=file2read.imcnp
          |  ^^^^ not expected here.
There was an error parsing "read".
sly: Syntax error at line 2, token=KEYWORD
```

My first thought: the file name and line number aren't always obvious. Also for some reason the underling is sometimes off by 1 and sometimes not, and I DON'T KNOW WHY!

**Comment by SterlingButters** [comment]
@MicahGale At a minimum I think you've got it: problematic lines of the input deck and their associated line numbers. I'm sure you have pretty good coverage of exceptions so in the cases in which you can provide more detail, I think it'd be worthwhile to do so. If you wanted to get really fancy, you could suggest a potential fix - perhaps even in such a way that the user can just "accept" the fix in the except block.

>  the file name and line number aren't always obvious

Can you explain the ambiguity? Can't reason why this might be difficult to ascertain

> Also for some reason the underling is sometimes off by 1 and sometimes not, and I DON'T KNOW WHY!

Eeek - a SLY problem? Honestly, tracebacks aren't perfect to begin with so as long as the line with the error is printed I think this would suffice in the meantime.

**Comment by MicahGale** [comment]
>> the file name and line number aren't always obvious

> Can you explain the ambiguity? Can't reason why this might be difficult to ascertain

Just glancing at the traceback it doesn't stand out and I missed it while I was glancing at it. Then again tracebacks are meant to be read carefully.

> If you wanted to get really fancy, you could suggest a potential fix - perhaps even in such a way that the user can just "accept" the fix in the except block.

Long term this could be good. This is all based on the rust compiler which makes these sort of suggestions, but that's really hard. As for making it fix it for you would require it be interactive that would be really complicated.
