### ISSUE TITLE
UnsupportedFeature raised when vertical input is behind comment 

### ISSUE THREAD

**Issue by SterlingButters** [idaholab/MontePy#363]
**Describe the bug**
It appears that MontePy tries to detect the vertical column input even if it is behind a `c`. 

You should be able to reproduce with something like:

`c # ...`

**Comment by MicahGale** [comment]
Good catch. 

At this point I feel like we can make this next release an honorary release in your name. All your bug reports have been very helpful. 

Any interest in contributing?

**Comment by SterlingButters** [comment]
lol - happy to help! There is undeniable utility in this tool - I want to see this project flourish. 

Interest? Yes! Time? No - unless I can scope the work into my normal job (which is honestly justifiable in my opinion). Let me see what I can do actually- it's worth the ask.
