### ISSUE TITLE
Line/Trailing Comments should not raise LineOverRunWarning

### ISSUE THREAD

**Issue by SterlingButters** [idaholab/MontePy#367]
**Is your feature request related to a problem? Please describe.**
Since MCNP ignores comments anyhow, this warning can just end up cluttering the console. Would make more sense if this exception was only raised for content (not comments) over the character limit.

**Comment by SterlingButters** [comment]
Changing the following lines in https://github.com/idaholab/MontePy/blob/5cf1e1ef701218ab6e6c6aa75861bfcc484f1358/montepy/input_parser/input_syntax_reader.py#L192:

```
old_line = line
line = line[:line_length]
if len(old_line) != len(line):
     warnings.warn(
          f"The line: {old_line} exceeded the allowed line length of: {line_length} for MCNP {mcnp_version}",
          errors.LineOverRunWarning,
            )
```

to

```
line = "".join(line.split('$')[0])
old_line = line
line = line[:line_length]
if old_line[0].lower() != 'c' and len(old_line) != len(line):
     warnings.warn(
          f"The line: {old_line} exceeded the allowed line length of: {line_length} for MCNP {mcnp_version}",
          errors.LineOverRunWarning,
            )
```

Solves the issue but not sure if this is consistent with the rest of the logic

**Comment by MicahGale** [comment]
That seems like it's in the right direction. Just have to be careful to not throw any information away at this stage.

This is redundant with #188, so I'm going to close it.

**Comment by MicahGale** [comment]
It's planned for the next minor release (0.3 ish).
