### ISSUE TITLE
Bugs in CI/CD workflow

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#407]
1. Changelog changes are checked for deploys. This should be skipped for main branch: https://github.com/idaholab/MontePy/actions/runs/9306739089/job/25616555261
2. GHA doesn't have permissions to push to main (and probably tags): https://github.com/idaholab/MontePy/actions/runs/9306739088

**Comment by MicahGale** [comment]
Related to #402.

**Comment by MicahGale** [comment]
So I came across this "solution": https://stackoverflow.com/questions/69263843/how-to-push-to-protected-main-branches-in-a-github-action

I have made @montepy-bot with a PAT, and added to the environment. However those expire every year. 

I think the second answer is better with deploy keys, and is the long term solution.

**Comment by MicahGale** [comment]
https://github.com/idaholab/MontePy/blob/develop/.github/workflows/deploy.yml#L37 This is out of order. Need to update changelog before building pages

**Comment by MicahGale** [comment]
> https://github.com/idaholab/MontePy/blob/develop/.github/workflows/deploy.yml#L37 This is out of order. Need to update changelog before building pages

Never mind. They are executed in the right order.

**Comment by MicahGale** [comment]
So after some discussion and more thinking: all of these solutions would lead to a security vulnerability.

I think instead we should:

1. ditch GHA deciding on the next version of the release.
2. Do tagging and changelog updating to be "manually" done.
3. Create a script to be ran by an admin that will be force pushed to develop during a release process.

Thoughts @tjlaboss?

**Comment by tjlaboss** [comment]
Probably 1 because it would break the continuity of CD the least

**Comment by MicahGale** [comment]
Oh I was listing these as tasks and not as alternatives.
