### ISSUE TITLE
Update Developer's Guide

### ISSUE THREAD

**Issue by tjlaboss** [idaholab/MontePy#416]
The developer's guide hasn't been updated in a while. Some of the information is out of date.

----

**Setting up and Typical Development Workflow**

> 2. Install the required packages. MontePy comes with two requirements files. One (requirements/common.txt) is for packages MontePy depends on. The other (requirements/dev.txt) is for packages that are generally necessary for developing. To install these simply run: `pip install -r requirements/dev.txt`

As of 5549e7645e1aba545b6a1301bebd42a58f5fc145, all requirements were moved to _pyproject.toml_.

----

> 12. Update the version, and authors as necessary. The version is stored in _montepy/\_\_init\_\_.py_. See the version numbering system described in _README.md_. The authors information is in _AUTHORS_ and _montepy/\_\_init\_\_.py_.

This is currently out of date. Should be updated once #407 is resolved and a new policy is defined, or deleted due to being superseded by the "Automated Versioning" section.

**Comment by MicahGale** [comment]
Right it would now be `pip install .[develop]`
