### ISSUE TITLE
Add logic to CI to disable changelog test

### ISSUE THREAD

**Issue by tjlaboss** [idaholab/MontePy#436]
**Is your feature request related to a problem? Please describe.**
Changes to meta things in the repository do not need to result in updates to the changelog. Modifications strictly to testing, documentation, license, etc. should be exempt from `changelog-test`.

**Describe the solution you'd like and alternatives you've considered**

Ideas, in order of descending preference:

 * Within `changelog-test`, check if modifications have been made to the `montepy/` module directory. If not, automatically pass.
 * Do not run `changelog-test` based on branch name wildcards, such as `doc-*` 
 * Add a magic keyword such as `no-changelog`

**Comment by MicahGale** [comment]
In the past we have included documentation and CI changes in the changelog. Are you proposing only including new features, deprecations, bugs, etc in the change log?

**Comment by tjlaboss** [comment]
I think that would make the changelog more relevant to the average user. Either way, having a switch to disable that specific test for minor changes would be nice.

**Comment by MicahGale** [comment]
Yeah I like moving more towards only testing for montepy changes

**Comment by tjlaboss** [comment]
logic:

```
Check for MontePy changes
  filters: 
    change: montepy/**
Check for changelog changes
  filters:
    change: doc/source/changelog.rst
if changelog didn't change:
  if MontePy changed:
    Changelog not updated when it should've been
    exit 1 
  else:
    Changelog didn't need to be updated
```

**Comment by MicahGale** [comment]
That looks pretty solid.

**Comment by tjlaboss** [comment]
Apparently GHA doesn't allow `else`
