### ISSUE TITLE
Decide how to test against Numpy 1 and 2

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#457]
Numpy 2.0 came out this June and is the first major release in a long time, which means some backwards compatibility is lost. Numpy 2.0 requires python 3.9. Due to this I saw that for python 3.8 we are testing against Numpy 1.24, and for Python >=3.9 we are testing against numpy 2.0. So right now we are accidentally testing against both major versions. However, this isn't a good spot to be.

So actions IMO:
1. Research what breaks in 2.0
2. Determine if this matters to us.
3. Decide if we need to peg to Numpy 1.xxx or Numpy 2.xxx
4. Decide if we need to do matrix testing against both major versions of numpy.

Thoughts @tjlaboss?

**Comment by tjlaboss** [comment]
# 1. What breaks in 2.0?

[NumPy 2.0 Migration Guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html)

[NumPy 2.0 Python API Removals](https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals)

# 2. Does this matter to us?

No, MontePy's usage of NumPy is basic and should continue to work the same.

### _data_inputs/fill.py_
```python
np.zeros(..., dtype=np.dtype(int))  # not broken
np.empty_like(..., dtype="O")       # not broken
```

### _data_inputs/transform.py_
```python
np.any(...)   # not broken
np.array([])  # not broken
np.array(values)  # not broken
```

There is also `np.ndarray` type hinting and an `np.ndarray` instantiation in the test suite.

# 3. Do we need to peg to Numpy 1.xxx or Numpy 2.xxx?

No, we are able to maintain compatibility with both 1 and 2 at this time.

# 4. Do need to do matrix testing against both major versions of numpy?

Yes, it would be a good idea to have at least one test for each, which will require an update to the CI once Python 3.8 is EOL'd.

**Comment by MicahGale** [comment]
Yeah... I'm not entirely sure the best way to test this in a `pyproject` compliant way?
Maybe install depenendencies. Uninstall numpy. Install requested version of numpy?

**Comment by tjlaboss** [comment]
Some ideas:

 - lazy hacky way: pick a specific `matrix.python-version` and manually set it to NumPy 1.x later on
 - lazy list way: `python-numpy-versions: [["3.9", "1.x.y"], ["3.10", "2.a.b"]]` and install requested version
 - test all version for both NumPy 1 and 2, and install requested version

**Comment by MicahGale** [comment]
I was thinking of using GHA to build a 2d matrix.
