### ISSUE TITLE
Error pickling MCNP_Problem: Cannot pickle 'generator' object

### ISSUE THREAD

**Issue by tjlaboss** [idaholab/MontePy#463]
Cannot pickle `montepy.MCNP_Problem` objects.

**Describe the bug**

Since v0.3.0, can no longer pickle `montepy.MCNP_Problem` for more complicated input decks. The `MCNP_Problem` contains an unpicklable generator object. Rolling back to v0.2.10 fixes this.

This occurs when the problem contains **tallies** (possibly other non-implemented data cards?).

This is not caught by _tests/test_interface.py::TestBrinyFermentation_ .

**To Reproduce / Error Message**

```python
>>> deck = montepy.read_input("path/to/input.imcnp")
>>> with open("path/to/pickle.pkl", 'wb') as pkl:
...    pickle.dump(deck, pkl)
TypeError: cannot pickle 'generator' object
```

**MCNP input file snippet**

```
MCNP Test Model for Tallies
1 1 20 -1000  imp:n,p=1 U=350 trcl=5
2 2 8  -1005  imp:n=1    imp:p=0.5
3 3 -1  1000 1005 -1010 imp:n,p=1
99 0 1010     imp:n,p=0
5 0   #99     imp:n,p=3 fill=350 (1 0 0 ) 

C surfaces
1000 SO 1
1005 RCC 0 1.5 -0.5 0 0 1 0.25
1010 SO 3

C data
C materials
C UO2 5 atpt enriched
m1        92235.80c           5 &
92238.80c          95
C Iron
m2        26054.80c        5.85
          26056.80c       91.75
          26057.80c        2.12
          26058.80c        0.28 
C water
m3        1001.80c           2
          8016.80c           1
MT3 lwtr.23t h-zr.20t h/zr.28t
C
C Tallies --> This breaks MontePy!
f7:n 1
C
C execution
ksrc 0 0 0 
kcode 100000 1.000 50 1050
phys:p j 1 2j 1
mode n p 
vol NO 2J 1 1.5 J
```

**Versions**

 - 0.3.0,
 -  0.3.1, 
 - 0.3.2

**Comment by MicahGale** [comment]
This sounds familiar to an old issue.

**Comment by tjlaboss** [comment]
Issue #189 

Something broke the ability to pickle inputs between then and now (for inputs with some as-yet unidentified complexity that is not tested).

**Comment by tjlaboss** [comment]
Tallies break it.

### test_tal.imcnp

```
MCNP Test Model for Tallies
1 1 20 -1000  imp:n,p=1 U=350 trcl=5
2 2 8  -1005  imp:n=1    imp:p=0.5
3 3 -1  1000 1005 -1010 imp:n,p=1
99 0 1010     imp:n,p=0
5 0   #99     imp:n,p=3 fill=350 (1 0 0 ) 

C surfaces
1000 SO 1
1005 RCC 0 1.5 -0.5 0 0 1 0.25
1010 SO 3

C data
C materials
C UO2 5 atpt enriched
m1        92235.80c           5 &
92238.80c          95
C Iron
m2        26054.80c        5.85
          26056.80c       91.75
          26057.80c        2.12
          26058.80c        0.28 $ trailing comment shouldn't move #458.
C water
m3        1001.80c           2
          8016.80c           1
MT3 lwtr.23t h-zr.20t h/zr.28t
C Tallies
f7:n 1
C execution
ksrc 0 0 0 
kcode 100000 1.000 50 1050
phys:p j 1 2j 1
mode n p 
vol NO 2J 1 1.5 J
```

**Comment by tjlaboss** [comment]
Created #468 to test this.

**Comment by MicahGale** [comment]
Thanks for doing this. I'm not sure if `tests/inputs/test.imcnp` is the best place for this though. Every time the file is updated a lot of tests have to be updated because I hard code in what the file is in a lot of places. Probably not the best test design.

**Comment by MicahGale** [comment]
Long term: https://docs.python.org/3/library/pickle.html#object.__reduce__ this is probably a solution that is needed along with #193.

**Comment by MicahGale** [comment]
Discovered this breaks `copy.deepcopy` as well now.

**Comment by tjlaboss** [comment]
This is suddenly very useful for some of my production work leveraging MontePy.
