### ISSUE TITLE
Moving parameters from Data block to Cell block neglects in-line comments

### ISSUE THREAD

**Issue by tjlaboss** [idaholab/MontePy#483]
**Describe the bug**

One can use `MCNP_Problem.print_in_data_block` to control whether a given cell parameter is written in the respective cell cards in the Cell block, or in a monolithic data card in the Data block.

When cell parameters in an existing input file are moved _from_ the Data block _to_ the Cell block, they are placed at the end of the relevant line as long as they fit. This results in them being after any `$ in-line comment`. When the parameters do fit on the line, they must be placed before the comment. 

**To Reproduce**

``` python
import montepy
deck = montepy.read_input("imp_cell.imcnp")
deck.print_in_data_block["IMP"] = False
deck.write_to_file("imp_data.imcnp", overwrite=True)
```

**MCNP input file snippet**

##### imp_cell.imcnp

```
Cell card printing error
C Cells
1 0  -100 $ 
2 0  +100 $ graveyard 

C Surfaces
100 so 10

C Data Cards
mode n
IMP:n 1 0 
```

##### imp_data.imcnp

```
Cell card printing error
C Cells
1 0  -100 $ IMP:n=1 
2 0  +100 $ graveyard IMP:n=0 

C Surfaces
100 SO 10

C Data Cards
mode n


```

**Version**

 - Versions 0.2 - 0.3.2

**Comment by MicahGale** [comment]
So added a new line after this would be needed. ... sigh

**Comment by tjlaboss** [comment]
If it doesn't fit, yes. If it fits, the options are:

- Always go to a new line. 
- If it fits within the character limit including trailing whitespace, append to the line, pushing the `$ ` comment to the right.
- If it fits within the character limit excluding trailing whitespace, eat up whitespace if it fits. This preserves alignment.

I prefer having parameters on their own line anyway, but frequently work with models where that is not the convention and the `$ ` comments are aligned.

**Comment by MicahGale** [comment]
Appending to the end as a new line is the easiest. I want to do that way.
