### ISSUE TITLE
Add support for reading from non-file steams

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#519]
**Is your feature request related to a problem? Please describe.**

It would be nice (mainly in testing) to do:

``` python
fh = io.StringIO()
fh.write(...)
fh.seek(0)
problem = montepy.read_input(fh)
```

**Describe the solution you'd like**
`montepy.read_input` should accept file streams.

**Describe alternatives you've considered**
None that I can think of.

**Additional context**
This is mostly for testing.

**Comment by tjlaboss** [comment]
The soulmate of #493

**Comment by MicahGale** [comment]
☯️

**Comment by MicahGale** [comment]
Exactly. This is why I needed it.

**Comment by MicahGale** [comment]
Turns out I forgot to implement this.
