### ISSUE TITLE
Document limitation to what materials can be parsed

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#542]
Let's add the known limitation to the documentation in a separate issue.

_Originally posted by @tjlaboss in https://github.com/idaholab/MontePy/pull/537#pullrequestreview-2297288561_

**Comment by tjlaboss** [comment]
![image](https://github.com/user-attachments/assets/ffa782fc-66b0-4420-90b2-703dae9c8e15)

The documentation should clarify:

 - That MontePy does not allow things among target-fraction pairs.
 - That MontePy requires the order `[Material number] [nuclide-fraction pairs] [parameters]`
 - What behavior the user will see if something outside this is encountered (error raised, mis-read material, material "read" but not understood, etc.)
