### ISSUE TITLE
Print active line when error occurs during reading

### ISSUE THREAD

**Issue by tjlaboss** [idaholab/MontePy#579]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when [...] I `read_input()` an an exception is raised, but it is unclear which part of my input file caused the exception.

**Describe the solution you'd like**
When an exception occurs during reading, include the line that was being read when the error was encountered in the error message.

**Describe alternatives you've considered**

One or more of the following would be helpful:

 * The active line
 * The line number
 * The entire card
 * The range of line numbers of the entire card

**Comment by MicahGale** [comment]
We could make an Exception wrapper that tries to add this information. It might not always be feasible always because this would involve wrapping essentially any call to an object. 

Something like:

``` python
try: 
    pass
except Exception as e:
    e.append("Came from line whatever.")
    raise e
```

**Comment by MicahGale** [comment]
Related to #127.

**Comment by MicahGale** [comment]
We could catch almost everything with a `__getattr__` wrapper. Is this worth it?
