### ISSUE TITLE
Allow easy adding of new materials

### ISSUE THREAD

**Issue by MicahGale** [idaholab/MontePy#93]
Right now to add a material you have to append it to: `problem.materials` *and* `problem.data_cards` which is very error-prone. I think this will require significant reimagination of what `data_cards` does. It has to balance storing original input order as well as allowing sorting of data cards.

**Comment by MicahGale** [comment]
I think for now at least the solution is to:

1. subclass `NumberedObjectCollection` something like `NumberedDataObjectCollection`. 
1. overwrite `append` which would insert the appended item after the last object of this type in `problem.data_inputs`.

Questions:

1. What should happen if a collection is detached from a problem? Should this `data_inputs` step be skipped or should a fatal error occur?

**Comment by tjlaboss** [comment]
> What should happen if a collection is detached from a problem? Should this data_inputs step be skipped or should a fatal error occur?

It should continue to work if the collection is detached from a problem. This might mean keeping a local list of `data_inputs` associated with the `NumberedDataObjectCollection` in an attempt to preserve their positions, or else just appending/append_renumbering the contents of `NumberedDataObjectCollection.values()` when next connected to a problem.

**Comment by tjlaboss** [comment]
> Should the appended object be linked to the new problem? Should the appended object be cloned?

The appended objects should be cloned. This is less likely to lead to user confusion.

**Comment by MicahGale** [comment]
I'm not sure if agree though. Having append always clone will lead to some weird behavior, and renumbering.
